#!/usr/bin/env python3
"""Génère specs/supported_parts_v1.md depuis la taxonomie.

Ce document avait dérivé jusqu'à dire l'inverse du code: il listait les quatre
ailes comme supportées et `wheel/rim` comme retirée, alors que la V1 fait
exactement le contraire. Le plus gênant était que `taxonomy.py` le citait comme
référence — le module écrit pour empêcher la dérive pointait vers un fichier
qui avait dérivé.

Une prose ne peut pas rester synchrone à la main. On la génère, et la CI
compare, exactement comme pour `configs/parts_yolo.yaml`.

    python scripts/build_parts_spec.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

from claimsight.domain.taxonomy import EXCLUDED_PARTS_V1, PART_CLASSES

#: Pourquoi chaque pièce a été écartée. Une exclusion sans motif finit par être
#: réintégrée par erreur, ou traînée sans que personne ose y toucher.
EXCLUSION_REASONS: dict[str, str] = {
    "side door": "ambiguous — superseded by the four explicit door classes",
    "rear windshield": "rare in source datasets, and not load-bearing for a claim",
    "left fender": "no equivalent class in the source dataset",
    "right fender": "no equivalent class in the source dataset",
    "rear left fender": "no equivalent class in the source dataset",
    "rear right fender": "no equivalent class in the source dataset",
}


def build_markdown() -> str:
    lines = [
        "<!-- GENERATED BY scripts/build_parts_spec.py — DO NOT EDIT BY HAND. -->",
        "<!-- Source of truth: claimsight/domain/taxonomy.py::PART_CLASSES -->",
        "",
        "# Supported parts — V1",
        "",
        f"The **{len(PART_CLASSES)} vehicle parts** the detector is trained on. The order is",
        "contractual: a part's index in this table is its YOLO class id, and changing",
        "it silently relabels every annotation.",
        "",
        "| id | Part |",
        "|---|---|",
    ]
    lines += [f"| {i} | `{name}` |" for i, name in enumerate(PART_CLASSES)]
    lines += [
        "",
        "Each annotated region carries one part, one damage type and one severity;",
        "see [`annotation_guidelines.md`](annotation_guidelines.md).",
        "",
        "## Excluded from V1",
        "",
        "| Part | Why |",
        "|---|---|",
    ]
    lines += [
        f"| `{name}` | {EXCLUSION_REASONS.get(name, 'no reason recorded')} |"
        for name in EXCLUDED_PARTS_V1
    ]
    lines += [
        "",
        "These keep a name in `EXCLUDED_PARTS_V1` so a mapping file can drop them",
        "**on purpose** rather than silently. They carry no class id and no training",
        "data.",
        "",
        "## Source of truth",
        "",
        "This file is generated. `claimsight/domain/taxonomy.py` governs; CI",
        "regenerates this document and fails on any difference, so it cannot drift",
        "from the code again.",
        "",
        "```bash",
        "python scripts/build_parts_spec.py",
        "```",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default="specs/supported_parts_v1.md")
    args = ap.parse_args()

    missing = [p for p in EXCLUDED_PARTS_V1 if p not in EXCLUSION_REASONS]
    if missing:
        raise SystemExit(
            f"Exclusion sans motif documenté: {missing}.\n"
            "Ajoutez-la à EXCLUSION_REASONS dans scripts/build_parts_spec.py."
        )

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_markdown(), encoding="utf-8")
    print(f"{out} écrit — {len(PART_CLASSES)} pièces, "
          f"{len(EXCLUDED_PARTS_V1)} exclusions.")


if __name__ == "__main__":
    main()
